# Nginx image to serve the bundler files
FROM nginx:alpine

# Copy the bundler files (already built by the workflow)
COPY ./www /usr/share/nginx/html

# Copy the custom Nginx configuration
COPY .github/nginx/default.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Health check
HEALTHCHECK --interval=30s --timeout=3s CMD wget --quiet --tries=1 --spider http://localhost/ || exit 1

# Command to run when container starts
CMD ["nginx", "-g", "daemon off;"]