name: Stripe Build and Publish Image

on:
  # Allow manual trigger
  workflow_dispatch:

  # Automatic trigger on new commits on any branch
  push:
    branches:
      - '**'
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    env:
      NODE_ENV: development
      NODE_OPTIONS: "--max-old-space-size=4096"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo sanitized GitHub ref and commit SHA
        run: |
          echo "GitHub commit SHA: ${{ github.sha }}"
          echo "GitHub ref name: ${{ github.ref_name }}"
          SANITIZED_REF_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          echo "SANITIZED_REF_NAME=${SANITIZED_REF_NAME}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build dependencies
        run: yarn build:deps

      - name: Build common, components, and app packages
        run: lerna run build --scope @codesandbox/common --scope @codesandbox/components --scope app

      - name: Build Sandpack
        run: yarn build:sandpack

      # Create a zip archive of the www folder
      - name: Create Zip Archive
        run: |
          cd www
          zip -r ../bundler.zip .
          cd ..
          echo "Created bundler.zip ($(du -h bundler.zip | cut -f1) in size)"

      # Upload the zip as an artifact - UPDATED TO V4
      - name: Upload Zip Archive
        uses: actions/upload-artifact@v4
        with:
          name: bundler-files
          path: bundler.zip
          retention-days: 90

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Create a dedicated directory for Docker build context
      - name: Prepare Docker build context
        run: |
          echo "Preparing Docker build context..."
          mkdir -p docker-context
          # Check if www directory exists
          if [ -d "www" ]; then
            echo "Copying www directory to build context"
            cp -r www docker-context/
          else
            echo "ERROR: www directory not found!"
            echo "Current directory contents:"
            ls -la
            exit 1
          fi

          # Create nginx config directory
          mkdir -p docker-context/.github/nginx

          # Create a basic nginx config
          echo 'server {
            listen 80;
            server_name _;

            # Enable gzip compression
            gzip on;
            gzip_types text/plain text/css application/javascript application/json;

            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;

                # Set CORS headers
                add_header "Access-Control-Allow-Origin" "*" always;
                add_header "Cache-Control" "public, max-age=86400, immutable";
            }

            # Special handling for worker files
            location ~ \.worker\.js$ {
                root /usr/share/nginx/html;
                add_header "Access-Control-Allow-Origin" "*" always;
                add_header "Content-Type" "application/javascript" always;
            }
          }' > docker-context/.github/nginx/default.conf

          # Create Dockerfile.bundler in the new context
          cat > docker-context/Dockerfile.bundler << 'EOF'
          FROM nginx:alpine
          COPY www /usr/share/nginx/html
          COPY .github/nginx/default.conf /etc/nginx/conf.d/default.conf
          EXPOSE 80
          HEALTHCHECK --interval=30s --timeout=3s CMD wget --quiet --tries=1 --spider http://localhost/ || exit 1
          CMD ["nginx", "-g", "daemon off;"]
          EOF

          echo "Contents of docker-context:"
          ls -la docker-context
          echo "Contents of docker-context/www (if it exists):"
          ls -la docker-context/www || echo "www directory not found in docker-context!"

      # Build and push Docker images for each target
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: docker-context
          file: docker-context/Dockerfile.bundler
          push: true
          tags: |
            stripe/librechat-sandpack:${{ github.sha }}
            stripe/librechat-sandpack:${{ env.SANITIZED_REF_NAME }}-${{ github.sha }}
            ${{ github.ref_name == 'main' && 'stripe/librechat-sandpack:latest' || '' }}
          platforms: linux/arm64
          target: node

      # Add a step to check the directory structure
      - name: Check directory structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of current directory:"
          ls -la
          echo "Contents of www directory (if it exists):"
          ls -la www || echo "www directory not found!"
